"use client";
import { useState } from "react";
import { CalendarDays, ChevronRight, Trophy } from "lucide-react";
import { SelectionHeader } from "../../../components/selection-header";

const matches = [
  { date: "Jeu. 24 sept. 2026", opponent: "Lettonie", venue: "E", score: "1 - 3", slug: "lettonie-kosovo-2026" },
  { date: "Dim. 27 sept. 2026", opponent: "Biélorussie", venue: "D", score: null },
  { date: "Sam. 10 oct. 2026", opponent: "Irlande du Nord", venue: "D", score: null },
  { date: "Mar. 13 oct. 2026", opponent: "Biélorussie", venue: "E", score: null, note: "Match joué en Bulgarie" },
] as const;

export default function SelectionCalendarPage() {
  const [season, setSeason] = useState("2026-2027");
  return <main className="min-h-screen bg-[radial-gradient(circle_at_85%_0,rgba(124,58,237,.18),transparent_30%),#090b10] px-5 py-7 text-slate-100 lg:px-12"><div className="mx-auto max-w-5xl"><SelectionHeader active="Calendrier"/><section className="surface mt-6 overflow-hidden"><header className="flex flex-col justify-between gap-4 border-b border-white/[.07] p-6 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-violet-300">Ligue des Nations C</p><h2 className="mt-2 text-xl font-semibold">Calendrier du Kosovo</h2><p className="mt-1 text-sm text-slate-400">Fenêtre internationale de septembre-octobre 2026.</p></div><label className="rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-sm"><span className="mr-2 text-slate-400">Saison</span><select value={season} onChange={event => setSeason(event.target.value)} className="bg-transparent font-semibold outline-none"><option className="bg-panel">2026-2027</option></select></label></header><div className="divide-y divide-white/[.07]">{matches.map((match, index) => { const teamLine = match.venue === "E" ? <>{match.opponent} <b className="mx-2 text-slate-600">—</b> Kosovo</> : <>Kosovo <b className="mx-2 text-slate-600">—</b> {match.opponent}</>; const content = <><span className="text-xs text-slate-400">{match.date}{match.note && <span className="mt-1 block text-[11px] text-slate-500">{match.note}</span>}</span><span className="font-semibold">{teamLine}</span><span className="hidden text-center text-xs text-slate-400 sm:block">{match.venue}</span><span className="inline-flex items-center justify-end gap-2 text-right text-xs text-violet-200">{match.score ? <strong className="rounded-lg bg-violet-400/15 px-2 py-1 text-sm text-white">{match.score}</strong> : <><Trophy size={14}/>Ligue des Nations C</>}</span></>; return match.slug ? <a href={`/selection/calendrier/${match.slug}`} key={match.date} className={`grid grid-cols-[1fr_auto] items-center gap-4 p-5 transition hover:bg-white/[.035] sm:grid-cols-[160px_1fr_38px_190px] ${index === 0 ? "bg-violet-500/10" : ""}`}>{content}<ChevronRight className="col-span-2 ml-auto -mt-8 text-violet-300 sm:hidden" size={17}/></a> : <article key={match.date} className="grid grid-cols-[1fr_auto] items-center gap-4 p-5 sm:grid-cols-[160px_1fr_38px_190px]">{content}</article>; })}</div></section><p className="mt-4 flex items-center gap-2 text-xs text-slate-500"><CalendarDays size={14}/>D = domicile · E = extérieur · Cliquez sur un match terminé pour ouvrir le compte-rendu.</p></div></main>;
}
