import { ChevronLeft, MapPin, Star, Trophy } from "lucide-react";
import { SelectionHeader } from "../../../../components/selection-header";

const stats = [
  ["Possession", "46 %", "54 %"], ["Tirs", "5", "20"], ["Tirs cadrés", "1", "10"], ["xG", "0,86", "2,47"], ["Corners", "2", "6"], ["Passes réussies", "90 %", "92 %"], ["Centres réussis", "5 %", "25 %"], ["Fautes", "6", "7"], ["Note moyenne", "6,7", "7,1"]
];

export default async function MatchPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  if (slug !== "lettonie-kosovo-2026") return <main className="grid min-h-screen place-items-center bg-ink text-white"><a className="text-violet-300" href="/selection/calendrier">Match introuvable — Retour au calendrier</a></main>;
  return <main className="min-h-screen bg-[radial-gradient(circle_at_85%_0,rgba(124,58,237,.18),transparent_30%),#090b10] px-5 py-7 text-slate-100 lg:px-12"><div className="mx-auto max-w-6xl"><SelectionHeader active="Calendrier"/><a href="/selection/calendrier" className="mt-7 inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ChevronLeft size={16}/>Retour au calendrier</a><section className="mt-5 overflow-hidden rounded-3xl border border-violet-400/20 bg-[linear-gradient(135deg,rgba(112,124,51,.38),rgba(8,11,20,.96)_62%)] p-7 text-center sm:p-10"><p className="inline-flex items-center gap-2 text-sm text-violet-100"><Trophy size={15}/>Ligue des Nations · Division C</p><div className="mt-5 flex items-center justify-center gap-5 text-xl font-semibold sm:gap-10 sm:text-3xl"><span>Lettonie</span><strong className="text-4xl sm:text-5xl">1 - 3</strong><span>Kosovo</span></div><p className="mt-4 text-sm text-slate-300">Jeudi 24 septembre 2026 <span className="mx-2 text-white/20">|</span> Skonto Stadium, Riga</p><p className="mt-3 inline-flex items-center gap-2 rounded-full bg-violet-400/15 px-3 py-1 text-sm text-violet-100"><Star size={14}/>Homme du match : Florian Hadergjonaj · 7,88</p></section><div className="mt-5 grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><section className="surface p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-300">Événements du match</p><div className="mt-5 space-y-4 border-l border-violet-300/25 pl-5"><Event time="6’" text="Edon Zhegrova ouvre le score"/><Event time="15’" text="Raimonds Krollis égalise pour la Lettonie" home/><Event time="24’" text="Fisnik Asllani redonne l’avantage au Kosovo"/><Event time="87’" text="Florent Muslija scelle la victoire, servi par Milot Rashica"/></div><div className="mt-7 rounded-2xl bg-white/[.04] p-4 text-sm text-slate-300"><p className="font-semibold text-white">Composition du Kosovo</p><p className="mt-2 leading-6">Muriç · Hadergjonaj, Rrahmani, Drešević, Hajdari, Paçarada · Rexhbeçaj, Abdullahu · Muslija, Asllani, Zhegrova</p></div></section><section className="surface p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-300">Statistiques du match</p><div className="mt-5 space-y-4">{stats.map(([label, home, away])=><div key={label}><div className="flex justify-between text-sm"><span>{home}</span><span className="text-slate-400">{label}</span><span className="font-semibold text-violet-200">{away}</span></div><div className="mt-2 flex h-2 gap-1"><div className="rounded-l-full bg-rose-400/55" style={{ width: `${Math.min(50, Number.parseFloat(home.replace(",", ".")) * 2 || 12)}%` }}/><div className="flex-1 rounded-r-full bg-violet-500/75"/></div></div>)}</div><p className="mt-7 flex items-center justify-center gap-2 text-sm text-slate-400"><MapPin size={15}/>Skonto Stadium · Riga, Lettonie</p></section></div></div></main>;
}

function Event({ time, text, home }: { time: string; text: string; home?: boolean }) { return <div><span className={`mr-3 inline-flex rounded-md px-2 py-1 text-xs font-bold ${home ? "bg-rose-400/15 text-rose-200" : "bg-violet-400/15 text-violet-200"}`}>{time}</span><span className="text-sm text-slate-300">{text}</span></div>; }
