"use client";
import type React from "react";
import { useEffect,useState } from "react";
import { Flag,Landmark,Shield,Trophy } from "lucide-react";
import { SelectionHeader } from "../../components/selection-header";
import { KosovoFlag } from "../../components/kosovo-flag";
import { HomeSettingEditor } from "../../components/home-setting-editor";
import { getSupabaseClient } from "../../lib/supabase";
const initial={name:"Kosovo",subtitle:"Équipe du Kosovo · UEFA · Europe",logo:"",background:"/images/fadil-vokrri-night.png",reputation:"Continentale",ranking:"65e",stadium:"Stade Fadil Vokrri",mandate:"21 juillet 2026"};
function Card({icon,label,value,href}:{icon:React.ReactNode;label:string;value:string;href?:string}){const content=<><div className="text-violet-300">{icon}</div><p className="mt-4 text-sm text-slate-400">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p>{href&&<p className="mt-2 text-xs font-semibold text-violet-300">Voir l’évolution →</p>}</>;return href?<a href={href} className="surface block p-5 transition hover:-translate-y-0.5 hover:border-violet-300/40">{content}</a>:<section className="surface p-5">{content}</section>}
export default function SelectionPage(){const[data,setData]=useState(initial);useEffect(()=>{const db=getSupabaseClient();db?.from("site_settings").select("value").eq("setting_key","selection_page").maybeSingle().then(({data:row})=>{if(row?.value)setData(x=>({...x,...row.value}))})},[]);return <main className="min-h-screen bg-[radial-gradient(circle_at_85%_0,rgba(124,58,237,.18),transparent_30%),#090b10] px-4 py-6 text-slate-100 sm:px-8 lg:px-14"><SelectionHeader active="Pays"/><section className="relative mt-7 overflow-hidden rounded-3xl border border-violet-400/20 bg-cover bg-center p-7 shadow-glow sm:p-10" style={{backgroundImage:`linear-gradient(90deg, rgba(7,9,20,.9), rgba(7,9,20,.56)), url(${data.background})`}}><div className="absolute right-4 top-4"><HomeSettingEditor settingKey="selection_page" title="Présentation de la sélection" value={data} fields={[{key:"name",label:"Nom du pays"},{key:"subtitle",label:"Description"},{key:"logo",label:"Logo ou drapeau",type:"image"},{key:"background",label:"Photo de fond",type:"image"},{key:"reputation",label:"Réputation"},{key:"ranking",label:"Classement FIFA"},{key:"stadium",label:"Stade habituel"},{key:"mandate",label:"Début du mandat"}]} onSaved={setData}/></div><div className="flex flex-col items-start gap-6 sm:flex-row sm:items-center">{data.logo?<img src={data.logo} alt={`Drapeau ${data.name}`} className="h-24 w-24 rounded-[30%] bg-white/5 object-contain p-2 shadow-2xl"/>:<KosovoFlag className="h-24 w-24 rounded-[30%] shadow-2xl"/>}<div><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-300">Votre pays</p><h2 className="mt-2 text-4xl font-semibold tracking-tight">{data.name}</h2><p className="mt-2 text-sm text-slate-300">{data.subtitle}</p></div></div></section><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card icon={<Shield size={17}/>} label="Réputation" value={data.reputation}/><Card icon={<Trophy size={17}/>} label="Classement FIFA" value={data.ranking} href="/selection/classement-fifa"/><Card icon={<Landmark size={17}/>} label="Stade habituel" value={data.stadium}/><Card icon={<Flag size={17}/>} label="Début de mandat" value={data.mandate}/></div></main>}
