"use client";
import { useState } from "react";
import { Trophy } from "lucide-react";
import { SelectionHeader } from "../../../components/selection-header";

const competitions = ["Ligue des Nations 2026/27", "Qualifications Euro 2028", "Euro 2028", "Matchs amicaux"];
const group = ["Arménie", "Kazakhstan", "Kosovo", "Lituanie"];

export default function SelectionCompetitionsPage() {
  const [competition, setCompetition] = useState(competitions[0]);
  const isNationsLeague = competition === competitions[0];
  return <main className="min-h-screen bg-ink px-5 py-7 text-slate-100 lg:px-12"><div className="mx-auto max-w-5xl"><SelectionHeader active="Compétitions"/><section className="surface mt-6 overflow-hidden"><header className="flex flex-col justify-between gap-4 border-b border-white/[.07] p-6 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-violet-300">Compétitions</p><h2 className="mt-2 text-xl font-semibold">{competition}</h2><p className="mt-1 text-sm text-slate-400">Parcours, classement et calendrier du Kosovo.</p></div><select value={competition} onChange={event => setCompetition(event.target.value)} className="rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-sm font-semibold outline-none">{competitions.map(item => <option key={item} className="bg-panel">{item}</option>)}</select></header>{isNationsLeague ? <div><div className="flex items-center gap-3 p-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-500/15 text-violet-300"><Trophy size={19}/></span><div><h3 className="font-semibold">Groupe 4 · Ligue des Nations C</h3><p className="mt-1 text-sm text-slate-400">Les deux premiers matchs débuteront en septembre 2026.</p></div></div><div className="grid grid-cols-[42px_1fr_42px_42px_42px_52px] gap-2 border-y border-white/[.07] px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-500"><span>#</span><span>Équipe</span><span className="text-center">J</span><span className="text-center">G</span><span className="text-center">N</span><span className="text-right">Pts</span></div><div className="divide-y divide-white/[.07]">{group.map((team, index) => <div key={team} className={`grid grid-cols-[42px_1fr_42px_42px_42px_52px] items-center gap-2 px-5 py-4 text-sm ${team === "Kosovo" ? "bg-violet-500/10" : ""}`}><span className="font-semibold text-slate-400">{index + 1}</span><span className="font-semibold">{team}</span><span className="text-center text-slate-400">0</span><span className="text-center text-slate-400">0</span><span className="text-center text-slate-400">0</span><span className="text-right font-semibold">0</span></div>)}</div></div> : <div className="grid place-items-center py-16 text-center"><Trophy size={32} className="text-violet-300"/><h3 className="mt-4 text-lg font-semibold">Aucune donnée pour {competition}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-slate-400">Les résultats et le tableau apparaîtront ici après import.</p></div>}</section></div></main>;
}
